version: "3"

services:
  app:
    build: .
    environment:
      FLASK_ENV: "docker_dev"
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    links:
      - "mongo:mongo"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"
