site_name: K-Cards
site_description: A web application to automatically moderate discussions.
site_author: K-Cards
repo_url: https://github.com/kcards/kcards

theme: readthedocs

nav:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
